org: mtheusbrito
app: activities
service: activities
frameworkVersion: "3"

params:
  default:
    dbName: activities-serverless
  dev:
    connectionString: mongodb://127.0.0.1:27017/${self:params.default.dbName}

provider:
  name: aws
  runtime: nodejs18.x
  environment:
    MONGODB_CONNECTION_STRING: ${param:connectionString}
    MONGODB_DB_NAME: ${param:dbName}

functions:
  sendResponse:
    handler: api/sendResponse.handler
    events:
      - httpApi:
          path: /api/results
          method: post
          request:
            schemas:
              application/json: ${file(./schemas/sendResponse.json)}
  getResult:
    handler: api/getResult.handler
    events:
      - httpApi:
          path: /api/results/{id}
          method: get

plugins:
  - serverless-offline
