org: mtheusbrito
app: activities
service: api
frameworkVersion: "3"

params:
  default:
    dbName: activities-serverless
  dev:
    connectionString: mongodb://127.0.0.1:27017/${self:params.default.dbName}
    salt: 5cDROEC8XHyNIt4Z9CNEfos34GAGPHCU
    jwt_secret: 9b5xB0IRW7fMkNHIgvY3v6UVHoOTwabG
  prod:
  
provider:
  name: aws
  runtime: nodejs18.x
  region: sa-east-1
  environment:
    MONGODB_CONNECTION_STRING: ${param:connectionString}
    MONGODB_DB_NAME: ${param:dbName}
    SALT: ${param:salt}
    JWT_SECRET: ${param:jwt_secret}
  httpApi:
    cors:
      allowedOrigins:
        - http://localhost:8080
        - http://localhost:3001
      allowedHeaders:
        - Content-Type
        - Authorization
      allowedMethods:
        - GET
        - POST
        - DELETE
        - PUT
        - PATCH
        - OPTIONS
        - HEAD
      allowCredentials: true
functions:
  sendResponse:
    handler: api/modules/results/controllers/sendResponse.handler
    events:
      - httpApi:
          path: /api/results
          method: post
          request:
            schemas:
              application/json: ${file(./schemas/sendResponse.json)}
  getResult:
    handler: api/modules/results/controllers/getResult.handler
    events:
      - httpApi:
          path: /api/results/{id}
          method: get
  login:
    handler: api/modules/account/controllers/login.handler
    events:
      - httpApi:
          path: /api/login
          method: post
          cors: true
          request:
            schemas:
              application/json: ${file(./schemas/login.json)}

plugins:
  - serverless-offline
  - serverless-plugin-common-excludes
  - serverless-plugin-include-dependencies
package:
  excludeDevDependencies: false
