org: mtheusbrito
app: activities
service: api
frameworkVersion: "3"

params:
  default:
    dbName: activities-serverless
  dev:
    connectionString: mongodb://127.0.0.1:27017/${self:params.default.dbName}
    salt: 5cDROEC8XHyNIt4Z9CNEfos34GAGPHCU
  prod:
  
provider:
  name: aws
  runtime: nodejs18.x
  region: sa-east-1
  environment:
    MONGODB_CONNECTION_STRING: ${param:connectionString}
    MONGODB_DB_NAME: ${param:dbName}
    SALT: ${param:salt}

functions:
  sendResponse:
    handler: api/sendResponse.handler
    events:
      - httpApi:
          path: /api/results
          method: post
          request:
            schemas:
              application/json: ${file(./schemas/sendResponse.json)}
  getResult:
    handler: api/getResult.handler
    events:
      - httpApi:
          path: /api/results/{id}
          method: get

plugins:
  - serverless-offline
  - serverless-plugin-common-excludes
  - serverless-plugin-include-dependencies
package:
  excludeDevDependencies: false
