org: mtheusbrito
app: activities
service: activities
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x

functions:
  sendResponse:
    handler: api/sendResponse.handler
    events:
      - httpApi:
          path: /api/results
          method: post
          request:
            schemas:
              application/json: ${file(./schemas/sendResponse.json)}
  getResult:
    handler: api/getResult.handler
    events:
      - httpApi:
          path: /api/results/{id}
          method: get

plugins:
  - serverless-offline
